name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Prettier check and auto-fix
        run: npx prettier --check . || npx prettier --write .
        continue-on-error: true

      - name: Biome format check
        run: npx @biomejs/biome format --check .
        continue-on-error: true

      - name: Biome lint
        run: npx @biomejs/biome lint --reporter=github .
        continue-on-error: true
