name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Lint, Type-check, Build, DB check
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Export environment variables
        run: |
          echo "NEON_DATABASE_URL=${NEON_DATABASE_URL:-$REPO_NEON_DATABASE_URL}" >> $GITHUB_ENV
          echo "AI_API_KEY=${AI_API_KEY:-$REPO_AI_API_KEY}" >> $GITHUB_ENV
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
          REPO_NEON_DATABASE_URL: ${{ vars.NEON_DATABASE_URL }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          REPO_AI_API_KEY: ${{ vars.AI_API_KEY }}

      - name: Prettier format check (TS/JS/Markdown)
        run: npx --yes prettier@3.3.3 --ignore-path .gitignore --check "**/*.{ts,tsx,js,jsx,md,mdx}"

      - name: Biome format check
        run: npx @biomejs/biome format --check .

      - name: Biome lint
        run: npx @biomejs/biome lint --reporter=github .

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Build (Next.js)
        run: npm run build

      - name: Test database connection (Neon)
        run: node scripts/db-check.mjs
